baseURL = "ukgt.github.io"
title = "UKGT"
theme = "hugo-theme-bootstrap"
#copyright = "Copyright © 2016-{year} Razon Yang. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "zh-tw"
#defaultContentLanguageInSubdir = true # If you use only one language comment this option
disableLanguages = ["fr", "zh-cn" ,"en"] # For disable one or more language

# Pagination 分頁
paginate = 5
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

 hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

  [privacy.disqus]
  disable = false

  [privacy.googleAnalytics]
  anonymizeIP = false
  disable = false
  respectDoNotTrack = false
  useSessionStorage = false

  #[privacy.instagram]
  #disable = false
  #simple = false

  [privacy.twitter]
  disable = false
  enableDNT = false
  simple = false

  [privacy.vimeo]
  disable = false
  enableDNT = false
  simple = false

  [privacy.youtube]
  disable = false
  privacyEnhanced = false
